### PR TITLE
Feat/issue 57 symbol details

### PR DESCRIPTION
**Pull request by amberleyromo**
wip - put up early at @shayc request

### CODE REVIEW

**Review by shayc — APPROVED** [review]
thanks, tidy! :) gonna move the render method to the end of the component to align with the rest of the code, let me know if you wanna change convention, also will move the symbols property out of the state

**Comment by amberleyromo** [comment]
I would be interested to discuss convention-- I like it toward the top because i almost feel like it serves as a pseudo-table of contents. You can get a glance without having to scroll all the way to the bottom. Thoughts?

**Comment by shayc** [comment]
I like the ui implementation to be at the bottom, but I agree with you regarding birds eye view when entering a component, how about we put the propTypes and defaultProps as static members or const at the very top. Can serve as a mini documentation

**Comment by amberleyromo** [comment]
Consistency is most important, that's fine. Just wondering why you like it at the bottom?

**Comment by shayc** [comment]
Well, the community tends to organize React component methods in the order they're being called:
Airbnb React/JSX Style Guide: [Ordering](https://github.com/airbnb/javascript/tree/master/react#ordering)

The styleguide also lists static methods first, so we can define `propTypes`, `defaultProps` first thing, what do you say?

**Pull request merged**
