### PR TITLE
justify content in the 'share board' screen

### LINKED ISSUE #852: justify-content: Space between on mobile screens
when the share board dialog is open on mobile screens the contents didn't see organized.
center contents to organize in a better way the style on a mobile browser.
image

### PR DESCRIPTION
**Pull request by angel208**
Modified the CSS of the BoardShare component to justify the content inside.

### CODE REVIEW

**Comment by angel208** [comment]
this is regarding the issue #852. I could not find how to link the pull request to the issue.

**Review by tomivm — COMMENTED** [review]
Fine. I can give you initial feedback. 
_Never commit lock files (package-lock.json, yarn.lock).
_This update modifies the content on large screens view to but I think looks good on both :)
_wait for Shay's or Martin's review. they are the professionals.

**Comment by shayc** [comment]
@angel208 thank you! I'll have a look at it tomorrow (as it is rather late now - 1:44am).
Wanted to comment regarding @tomivm "Never commit lock files (package-lock.json, yarn.lock)."
Actually it is considered a [best practice](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) to commit the `package-lock.json` or `yarn.lock` file - but never both. In our repository we have both files which can possibly result in bugs in CI. I'll remove one of them in a future PR (soon).

**Review by martinbedouret — APPROVED** [review]

**Comment by shayc** [comment]
@angel208 thank you for your first contribution! 🚀 your code was merged into the repository and will be uploaded to production in the next cycle!

**Pull request merged**
