### PR TITLE
Fix focus style for output bar when dark theme is enabled

### LINKED ISSUE #695: When dark theme is on, when the output bar is clicked, it highlights the bar with white color so the text below the symbols can’t be seen because the text is also in white color.
When dark theme is on, when the output bar is clicked, it highlights the bar with white color so the text below the symbols can’t be seen because the text is also in white color (screenshot in the attachment). I don’t know if users track the symbols and the text while the speech for whole sentences is reproduced, so I don’t know how big of a problem this is.
Screenshot_20200429-185724_Cboard

### PR DESCRIPTION
**Pull request by sylvansson**
Before and after:

image
image

Close #695

### CODE REVIEW

**Comment by sylvansson** [comment]
@martinbedouret I revised my PR. Instead of defining a new class with a `--dark` suffix (see 0d7cb71), I decided to take @shayc's approach in 01e78cf and add the `is-dark` class to the `App` component when dark mode is enabled. 

This saves us the trouble of passing the `darkThemeActive` prop around, and of having to add a class to each component that needs special styling in dark mode.

There are three components that still use the other approach:

- `Board`;
- `Navbar`;
- `SymbolOutput`.

I can update them in this PR if you'd like.

**Comment by martinbedouret** [comment]
@sylvansson I agree with you and I think your approach is better.
It would be great if you can work into your comments about components using the other approach as well.
Thank you !

**Comment by sylvansson** [comment]
Hi @martinbedouret, just to be sure, you're saying you want me to update the remaining three components in this PR?

**Comment by martinbedouret** [comment]
Yes @sylvansson , you are right.

**Comment by sylvansson** [comment]
Great, I'll make the changes tonight.

**Review by martinbedouret — APPROVED** [review]
@sylvansson this is improving the code definitely. You simplified it using this approach. Thank you !

**Pull request merged**
